language: php
php:
    - 5.5
    - 5.4
    - hhvm

before_script:
- wget https://scrutinizer-ci.com/ocular.phar
     
script:
    - phpunit --bootstrap test/config.php --coverage-clover build/logs/clover.xml test
	
after_script:
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
